travis:
  secure:
    BINSTAR_TOKEN: VIVjSscBpsCXoOaMn1fckIUKRAOI1h68SxKV77vfjPYvpUSlZrwBGfdiEYTGn6JdCNrRqYU1wqdeNAfhs8H5nOohOe9XTXUpWBAA2bo7dKg6vdg6mVDpPseCLXi7M0+Zzl9IwSnXrubIS4grBBhKvj8Bqe3Ukw/xiLsqj5v3yeFRSFrmfWelKHaAnCgeu2EPBVJ4M7EWORwwBKN8ytRR2XYfYoQtMb9iwg4AYcyqdrOKxhoh4sRZIwUwBdRLBQs9kpqY2RIfDrBHHQJ5JbNmGuDD4KENu8GcedDoNETcvryqjdijMXMF7HsCtVVmXzZI96a/w1+epgACfyxnhXyGb9xm9kN5CsjU5geI3l4k1l14nfAA/gx+o00mLFldqkq5kZrnZAkUe3C5B6fFZU+yK0wNGC6rRyn17bVRiF2bfVjl0mg0E3+Y36CPx9VG/IqtYjQ3fm4/myENFN0aG4Ie7jiBwNN/leUMdJmsMWzdK2Kk4DeGiffEcYGCeuyfxTGLeKinNRy4C/JsGvYhlWRbb0jDWy7tpiH28ds6+rcszXVLrzeYn0B6X0eyXodoFiB2/lmFgLTvtws2huLP4nW+LbINntblONwnokLt9xx0JOedl6gT4+ZHXaez6e7ndQSxm6VFTNzFznMK4XrhE7lcqNO/iMOuR6m7ZSr7fGoqf3E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
